EF_Book_SportsStore/Controllers/CategoriesController.cs
using EF_Book_SportsStore.Models;
using EF_Book_SportsStore.Models.Pages;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EF_Book_SportsStore.Controllers
{
    public class CategoriesController : Controller
    {
        private ICategoryRepository repository;
        public CategoriesController(ICategoryRepository repository) => this.repository = repository;

        public IActionResult Index(QueryOptions options) => View(repository.GetCategories(options));

        [HttpPost]
        public IActionResult AddCategory(Category category)
        {
            repository.AddCategory(category);
            return RedirectToAction("Index");
        }

        public IActionResult EditCategory(Guid categoryId)
        {
            ViewBag.EditId = categoryId;
            return View("Index", repository.Categories);
        }

        [HttpPost]
        public IActionResult UpdateCategory(Category category)
        {
            repository.UpdateCategory(category);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteCategory(Category category)
        {
            repository.DeleteCategory(category);
            return RedirectToAction("Index");
        }
    }
}

EF_Book_SportsStore/Controllers/OrdersController.cs
using EF_Book_SportsStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EF_Book_SportsStore.Controllers
{
    public class OrdersController : Controller
    {
        private IRepository productRepository;
        private IOrdersRepository ordersRepository;
        public OrdersController(IRepository productRepository, IOrdersRepository ordersRepository)
        {
            this.productRepository = productRepository;
            this.ordersRepository = ordersRepository;
        }

        public IActionResult Index() => View(ordersRepository.Orders);

        public IActionResult EditOrder(Guid orderId)
        {
            var products = productRepository.Products;
            Order order = orderId == default(Guid) ? new Order() : ordersRepository.GetOrder(orderId);
            IDictionary<Guid, OrderLine> linesMap = order.Lines?.ToDictionary(l => l.ProductId) ?? new Dictionary<Guid, OrderLine>();
            ViewBag.Lines = products.Select(p => linesMap.ContainsKey(p.ProductId) ? linesMap[p.ProductId] : new OrderLine { Product = p, ProductId = p.ProductId, Quantity = 0 });
            return View(order);
        }

        [HttpPost]
        public IActionResult AddUpdateOrder(Order order)
        {
            order.Lines = order.Lines.Where(l => l.OrderLineId != default(Guid) || (l.OrderLineId == default(Guid) && l.Quantity > 0)).ToArray();
            if (order.OrderId == default(Guid))
            {
                ordersRepository.AddOrder(order);
            }
            else
            {
                ordersRepository.UpdateOrder(order);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteOrder(Order order)
        {
            ordersRepository.DeleteOrder(order);
            return RedirectToAction("Index");
        }
    }
}

EF_Book_SportsStore/Views/Shared/PageOptions.cshtml
<div class="container-fluid mt-2">
    <div class="row m-1">
        <div class="col"></div>

        <div class="col-1">
            <label class="col-form-label">Поиск</label>
        </div>

        <div class="col-3">
            <select form="pageform" name="options.SearchPropertyName" class="form-control">
                @foreach (var s in ViewBag.Searches as string[])
	            {
		            <option value="@s" selected="@(Model.Options.SearchPropertyName == s)">
                        @(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))
                    </option>
	            }
            </select>
        </div>

        <div class="col">
            <input form="pageform" class="form-control" name="options.SearchTerm" value="@Model.Options.SearchTerm" />
        </div>

        <div class="col-1 text-right">
            <button form="pageform" class="btn btn-secondary" type="submit">Поиск</button>
        </div>

        <div class="col"></div>
    </div>

    <div class="row m-1">
        <div class="col"></div>

        <div class="col-1">
            <label class="col-form-label">Сортировка</label>
        </div>

        <div class="col-3">
            <select form="pageform" name="options.OrderPropertyName" class="form-control">
                @foreach (var s in ViewBag.Sorts as string[])
                {
                    <option value="@s" selected="@(Model.Options.OrderPropertyName == s)">@(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))</option>
                }
            </select>
        </div>

        <div class="col form-check form-check-inline">
            <input form="pageform" type="checkbox" name="Options.DescendingOrder" id="Options.DescendingOrder" class="form-check-input" value="true" checked="@Model.Options.DescendingOrder" />
            <label class="form-check-label">Descending Order</label>
        </div>

        <div class="col-1 text-right">
            <button form="pageform" class="btn btn-secondary" type="submit">Отсортировать</button>
        </div>

        <div class="col"></div>
    </div>

</div>

EF_Book_SportsStore/Views/Shared/Pages.cshtml
<form id="pageform" method="get" class="form-inline d-inline-block">

    <button name="options.CurrentPage" value="@(Model.CurrentPage - 1)" class="btn btn-outline-primary @(!Model.HasPreviousPage ? "disabled" : "")" type="submit">Назад</button>

    @for (int i = 1; i <= 3 && i <= Model.TotalPages; i++)
    {
        <button name="options.CurrentPage" value="@i" type="submit" class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">@i</button>
    }

    @if (Model.CurrentPage > 3 && Model.TotalPages - Model.CurrentPage >= 3)
    {
        @:...
        <button class="btn btn-outline-primary active">@Model.CurrentPage</button>
    }

    @if (Model.TotalPages > 3)
    {
        @:...
        @for (int i = Math.Max(4, Model.TotalPages - 2); i <= Model.TotalPages; i++)
        {
            <button name="options.CurrentPage" value="@i" type="submit" class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">@i</button>
        }
    }

    <button name="options.CurrentPage" value="@(Model.CurrentPage + 1)" type="submit" class="btn btn-outline-primary @(!Model.HasNextPage ? "disabled" : "")">Далее</button>

    <select name="options.PageSize" class="form-control ml-1 mr-1">
        @foreach (var item in new int[] { 10, 25, 50, 100 })
        {
            <option value="@item" selected="@(Model.PageSize == item)">@item</option>
        }
    </select>

    <input type="hidden" name="options.CurrentPage" value="1" />
    <button type="submit" class="btn btn-secondary">Количество товарок на странице</button>

</form>

EF_Book_SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sports Store</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <style>
        .placeholder {
            visibility: collapse;
            display: none;
        }
        .placeholder:only-child {
            visibility: visible;
            display: flex;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row p-2">
            <div class="col-2">
                <a asp-controller="Home" asp-action="Index" class="@GetClassForButton("Home")">Товары</a>
                <a asp-controller="Categories" asp-action="Index" class="@GetClassForButton("Categories")">Категории</a>
                <a asp-controller="Orders" asp-action="Index" class="@GetClassForButton("Orders")">Заказы</a>
            </div>
            <div class="col">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

@functions {
    string GetClassForButton(string controller)
    {
        return "btn btn-block " + (ViewContext.RouteData.Values["controller"] as string == controller ? "btn-primary" : "btn-outline-primary");
    }
}